[preferred]
# Usa il portale wlroots per screenshot e screen cast (condivisione schermo)
org.freedesktop.impl.portal.Screenshot=wlr
org.freedesktop.impl.portal.ScreenCast=wlr

# Usa il portale di GNOME o GTK for il selettore dei file, notifiche e preferenze
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.Notification=gtk

# Comportamento predefinito per tutto il resto
default=gtk
